# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "eu-north-1"            # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: "medical-rag"           # set this to your Amazon ECR repository name
  ECS_SERVICE: "medical-rag-ecs"                 # set this to your Amazon ECS service name
  ECS_CLUSTER: "medical-rag-cluster"                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: "terraform/task_definition.json" # set this to the path to your Amazon ECS task definition
                                           # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: "medical-rag-container"           # set this to the name of the container in the

  ECR_PUBLIC_REGION: "us-east-1"    # ECR Public's control-plane API only lives here
                                               # containerDefinitions section of your task definition

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: get info
        run: echo "repo=${{ github.repository }} ref=${{ github.ref }} branch=${{ github.ref_name }}"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::431451851290:role/github-actions-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.ECR_PUBLIC_REGION }}   # must be us-east-1 for ECR Public auth

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: c0w4z1m9/medical-rag
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
